AWSTemplateFormatVersion: 2010-09-09
Description:
  This template creates the GuardDuty delivery KMS key

Parameters:
  ProjectName:
    Type: String
    Description: Project Name
    MaxLength: 20
  LogArchiveAccountId:
    Type: String
    Description: AWS Account ID of the Control Tower Log Archive account.
  AutomationAccountId:
    Type: String
    Description: Automation Account ID

Conditions:
  LogArchiveAccountIdEmpty: !Equals
  - !Ref LogArchiveAccountId
  - ""

Resources:
  GuardDutyDeliveryKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub "${ProjectName} GuardDuty Delivery Key"
      EnableKeyRotation: True
      KeyPolicy:
        Version: 2012-10-17
        Id: !Sub "${ProjectName}-guardduty-delivery-key"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Action: 'kms:*'
            Resource: '*'
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
          - Sid: Allow GuardDuty to encrypt logs
            Effect: Allow
            Action: kms:GenerateDataKey
            Resource: '*'
            Principal:
              Service: guardduty.amazonaws.com
          - Sid: Allow alias creation during setup
            Effect: Allow
            Action: kms:CreateAlias
            Condition:
              StringEquals:
                kms:CallerAccount: !Sub ${AWS::AccountId}
                kms:ViaService: !Sub cloudformation.${AWS::Region}.amazonaws.com
            Resource: '*'
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
          - Sid: Allow accounts access
            Effect: Allow
            Action:
            - kms:Decrypt
            - kms:DescribeKey
            Resource: '*'
            Principal:
              AWS:
                - !If [LogArchiveAccountIdEmpty, !Ref AWS::NoValue, !Sub "arn:${AWS::Partition}:iam::${LogArchiveAccountId}:root"]
                - !Sub "arn:${AWS::Partition}:iam::${AutomationAccountId}:root"
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root

  GuardDutyDeliveryKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${ProjectName}-guardduty-delivery-key"
      TargetKeyId: !Ref GuardDutyDeliveryKey

  GuardDutyDeliveryKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/${ProjectName}/DELIVERY_KEY_ARN"
      Description: GuardDuty Delivery KMS Key ARN
      SecretString: !Sub '{"GuardDutyDeliveryKeyArn":"${GuardDutyDeliveryKey.Arn}"}'
      KmsKeyId: !GetAtt GuardDutyDeliveryKey.Arn

  GuardDutyDeliveryKeySecretPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref GuardDutyDeliveryKeySecret
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
          - Action: secretsmanager:GetSecretValue
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
                - !If [LogArchiveAccountIdEmpty, !Ref AutomationAccountId, !Sub "arn:aws:iam::${LogArchiveAccountId}:root"]
            Resource: '*'
            Condition:
              ForAnyValue:StringEquals:
                secretsmanager:VersionStage: AWSCURRENT

Outputs:
  GuardDutyDeliveryKeyArn:
    Description: GuardDuty Delivery KMS Key ARN
    Value: !GetAtt GuardDutyDeliveryKey.Arn